import type { Metadata } from "next";
import Link from "next/link";
import BrandMark from "@/components/BrandMark";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms",
  description: "Terms of use for HoopTrainer AI.",
};

const termsSections = [
  {
    title: "Product Use",
    body:
      "You may use HoopTrainer AI for personal training planning, workout tracking, and basketball skill development. You must not abuse the platform, interfere with other users, scrape private data, or attempt unauthorized access.",
  },
  {
    title: "Training Disclaimer",
    body:
      "Training suggestions generated by the app are informational only. Always use judgment, train within your current level, warm up properly, and speak with a qualified coach or medical professional if you have pain, injury history, or health concerns.",
  },
  {
    title: "Accounts",
    body:
      "You are responsible for the security of your account credentials and the activity associated with your account. Keep your password private and notify the team if you believe your account has been compromised.",
  },
  {
    title: "Saved Content",
    body:
      "Workout notes, saved AI plans, and profile details are provided for organization and training reference. You are responsible for reviewing any generated plan before performing it.",
  },
  {
    title: "Availability",
    body:
      "We may improve, modify, or temporarily suspend parts of the product as the platform evolves. We aim to keep the service reliable, but uptime and uninterrupted access cannot be guaranteed at all times.",
  },
  {
    title: "Contact",
    body:
      "For support or policy questions, contact support@hooptrainer.ai. We will use that channel for product, account, and terms-related questions.",
  },
];

export default function TermsPage() {
  return (
    <div className="legal-page-shell">
      <main className="legal-page-main">
        <nav className="legal-topbar">
          <BrandMark size="sm" />
          <div className="legal-nav-actions">
            <Link href="/">Landing page</Link>
            <Link href="/dashboard">Dashboard</Link>
          </div>
        </nav>

        <section className="legal-hero">
          <div>
            <div className="section-kicker">HOOPTRAINER AI AGREEMENT</div>
            <h1>Terms of Use</h1>
            <p>
              The ground rules for using HoopTrainer AI to organize basketball workouts, save training plans,
              and generate AI-assisted practice ideas.
            </p>
          </div>
          <div className="legal-hero-card">
            <span>Last updated</span>
            <strong>April 26, 2026</strong>
            <small>Use the app responsibly and review every plan before training.</small>
          </div>
        </section>

        <section className="legal-summary-grid" aria-label="Terms summary">
          <div>
            <span>01</span>
            <strong>Train responsibly</strong>
            <p>The app helps with planning, but it is not medical advice.</p>
          </div>
          <div>
            <span>02</span>
            <strong>Protect accounts</strong>
            <p>Keep credentials private and use the product within normal access rules.</p>
          </div>
          <div>
            <span>03</span>
            <strong>Review AI plans</strong>
            <p>Generated workouts should be checked before you perform them.</p>
          </div>
        </section>

        <section className="legal-content-card">
          {termsSections.map((section) => (
            <article key={section.title} className="legal-section">
              <h2>{section.title}</h2>
              <p>{section.body}</p>
            </article>
          ))}
        </section>

        <section className="legal-bottom-actions">
          <div>
            <strong>Done reading?</strong>
            <p>Go back to training or return to the public landing page.</p>
          </div>
          <div>
            <Link className="legal-primary-action" href="/dashboard">Back to dashboard</Link>
            <Link className="legal-secondary-action" href="/">Back to landing page</Link>
          </div>
        </section>
      </main>
      <SiteFooter compact />
    </div>
  );
}
