import type { Metadata } from "next";
import Link from "next/link";
import type { CSSProperties } from "react";
import BrandMark from "@/components/BrandMark";
import SiteFooter from "@/components/SiteFooter";

export const metadata: Metadata = {
  title: "Terms",
  description: "Terms of use for HoopTrainer AI.",
};

const sectionStyle: CSSProperties = {
  display: "grid",
  gap: 10,
  padding: "22px 0",
  borderTop: "1px solid rgba(255,255,255,0.08)",
};

export default function TermsPage() {
  return (
    <div style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
      <main
        style={{
          minHeight: "100vh",
          padding: "56px 18px 88px",
          flex: "1 0 auto",
        }}
      >
        <div
          style={{
            width: "min(860px, 100%)",
            margin: "0 auto",
            background: "rgba(20, 27, 44, 0.84)",
            border: "1px solid rgba(255,255,255,0.08)",
            borderRadius: 24,
            boxShadow: "0 24px 60px rgba(0,0,0,0.3)",
            padding: "30px 26px",
            backdropFilter: "blur(12px)",
          }}
        >
          <div style={{ display: "flex", justifyContent: "space-between", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
            <BrandMark size="sm" />
            <div style={{ display: "flex", gap: 14, flexWrap: "wrap" }}>
              <Link href="/" style={{ fontWeight: 700 }}>Back home</Link>
              <Link href="/dashboard" style={{ fontWeight: 700, color: "var(--accent-2)" }}>Dashboard</Link>
            </div>
          </div>

          <header style={{ display: "grid", gap: 10, padding: "24px 0 18px" }}>
            <p className="helper" style={{ margin: 0 }}>Last updated: April 14, 2026</p>
            <h1 style={{ fontSize: 34, lineHeight: 1.1 }}>Terms of Use</h1>
            <p className="helper" style={{ margin: 0, maxWidth: 680 }}>
              HoopTrainer AI is designed to help athletes organize basketball training ideas and workouts.
              By using the app, you agree to use it responsibly and understand that it is not medical advice.
            </p>
          </header>

          <section style={sectionStyle}>
            <h2 style={{ fontSize: 22 }}>Product Use</h2>
            <p className="helper" style={{ margin: 0 }}>
              You may use HoopTrainer AI for personal training planning, workout tracking, and basketball skill development.
              You must not use the service to abuse the platform, interfere with other users, or attempt unauthorized access.
            </p>
          </section>

          <section style={sectionStyle}>
            <h2 style={{ fontSize: 22 }}>Training Disclaimer</h2>
            <p className="helper" style={{ margin: 0 }}>
              Training suggestions generated by the app are informational only. Always use judgment, train within your level,
              and speak with a qualified coach or medical professional when you have health concerns, injury history, or pain.
            </p>
          </section>

          <section style={sectionStyle}>
            <h2 style={{ fontSize: 22 }}>Accounts</h2>
            <p className="helper" style={{ margin: 0 }}>
              You are responsible for the security of your account credentials and the activity associated with your account.
              Keep your password private and notify the team if you believe your account has been compromised.
            </p>
          </section>

          <section style={sectionStyle}>
            <h2 style={{ fontSize: 22 }}>Availability</h2>
            <p className="helper" style={{ margin: 0 }}>
              We may improve, modify, or temporarily suspend parts of the product as the platform evolves. We aim to keep the
              service reliable, but uptime and uninterrupted access cannot be guaranteed at all times.
            </p>
          </section>

          <section style={sectionStyle}>
            <h2 style={{ fontSize: 22 }}>Contact</h2>
            <p className="helper" style={{ margin: 0 }}>
              For support or policy questions, contact <a href="mailto:support@hooptrainer.ai">support@hooptrainer.ai</a>.
            </p>
          </section>
        </div>
      </main>
      <SiteFooter compact />
    </div>
  );
}
